[bar]
  bar = ["#3e4144", "#3e4144"]

[text]
  text = ["#3e4144", "#3e4144"]

[active]
  active = ["#3e4144", "#3e4144"]

[inactive]
  inactive = ["#5B686D", "#5B686D"]

[urgent]
  urgent = ["#b48ead", "#b48ead"]

[this_screen]
  this_screen = ["#66d9ef", "#66d9ef"]

[other_screen]
  other_screen = ["#5dc1b9", "#5dc1b9"]

[color1]
  color1 = ["#fd971f", "#fd971f"]

[color2]
  color2 = ["#ae81ff", "#ae81ff"]

[color3]
  color3 = ["#66d9ef", "#66d9ef"]
