[hack]
  hack = [
    "Hack Nerd Font",
    "Hack Nerd Font",
    "Hack Nerd Font",
  ]

[ubuntu]
  ubuntu = [
    "UbuntuMono Nerd Font",
    "UbuntuMono Nerd Font",
    "UbuntuMono Nerd Font"
  ]

[mononoki]
  mononoki = [
    "mononoki Nerd Font",
    "mononoki Nerd Font",
    "mononoki Nerd Font"
  ]

[agave]
  agave = [
    "agave Nerd Font",
    "agave Nerd Font",
    "agave Nerd Font"
  ]

[jetbrains]
  jetbrains = [
    "JetBrainsMono Nerd Font",
    "JetBrainsMono Nerd Font",
    "JetBrainsMono Nerd Font",
  ]
